language: scala

scala:
  - 2.13.2
  - 2.12.11

jobs:
  include:

    - name: 'Scala 2.12 / Scala.JS 0.6 / Graal 20.0 Java 11'
      scala: 2.12.11
      env: GRAAL_VER=20.0.0 JAVA_VER=11 SCALAJS_VERSION=0.6.33

    - name: 'Scala 2.13 / Scala.JS 0.6 / Graal 20.0 Java 11'
      scala: 2.13.2
      env: GRAAL_VER=20.0.0 JAVA_VER=11 SCALAJS_VERSION=0.6.33

#    - name: 'Scala 2.12 / Scala.JS 0.6 / Graal 20.0 Java 8'
#      scala: 2.12.11
#      env: GRAAL_VER=20.0.0 JAVA_VER=8 SCALAJS_VERSION=0.6.33
#
#    - name: 'Scala 2.13 / Scala.JS 0.6 / Graal 20.0 Java 8'
#      scala: 2.13.2
#      env: GRAAL_VER=20.0.0 JAVA_VER=8 SCALAJS_VERSION=0.6.33

    - name: 'Scala 2.12 / Scala.JS 1.0 / Graal 20.0 Java 11'
      scala: 2.12.11
      env: GRAAL_VER=20.0.0 JAVA_VER=11 SCALAJS_VERSION=

    - name: 'Scala 2.13 / Scala.JS 1.0 / Graal 20.0 Java 11'
      scala: 2.13.2
      env: GRAAL_VER=20.0.0 JAVA_VER=11 SCALAJS_VERSION=

before_install:
  - wget https://github.com/sormuras/bach/raw/master/install-jdk.sh

install:
  - . $HOME/.nvm/nvm.sh
  - nvm install stable
  - nvm use stable
  - export NODE_PATH="$(npm config get prefix)"/lib/node_modules
  - npm install
  - npm install jsdom source-map-support
  - . ./install-jdk.sh --url "https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-${GRAAL_VER}/graalvm-ce-java${JAVA_VER}-linux-amd64-${GRAAL_VER}.tar.gz"

script:
  - sbt ++$TRAVIS_SCALA_VERSION 'set parallelExecution in ThisBuild := false' test

before_cache:
  - rm -f $HOME/.ivy2/.sbt.ivy.lock
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete
  - find $HOME/.sbt -name "*.lock" -type f -delete
cache:
  directories:
    - $HOME/.coursier
    - $HOME/.ivy2/cache
    - $HOME/.sbt

