language: scala

scala:
  - 2.12.8

env:
  - GRAAL_VER=19.0.0

before_install:
- wget https://github.com/sormuras/bach/raw/master/install-jdk.sh

install:
  - . $HOME/.nvm/nvm.sh
  - nvm install 10
  - nvm use 10
  - export NODE_PATH="$(npm config get prefix)"/lib/node_modules
  - npm install
  - npm install jsdom@9.12.0 source-map-support
  - . ./install-jdk.sh --url "https://github.com/oracle/graal/releases/download/vm-${GRAAL_VER}/graalvm-ce-linux-amd64-${GRAAL_VER}.tar.gz"

script:
  - sbt ++$TRAVIS_SCALA_VERSION 'set parallelExecution in ThisBuild := false' test

before_cache:
  - rm -f $HOME/.ivy2/.sbt.ivy.lock
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete
  - find $HOME/.sbt -name "*.lock" -type f -delete
cache:
  directories:
    - $HOME/.coursier
    - $HOME/.ivy2/cache
    - $HOME/.sbt

